package com.jqwong.music.repository.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jqwong.music.repository.entity.Artist;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTIST".
*/
public class ArtistDao extends AbstractDao<Artist, Long> {

    public static final String TABLENAME = "ARTIST";

    /**
     * Properties of entity Artist.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property UserId = new Property(1, Long.class, "UserId", false, "USER_ID");
        public final static Property ArtistId = new Property(2, Long.class, "ArtistId", false, "ARTIST_ID");
        public final static Property Name = new Property(3, String.class, "Name", false, "NAME");
        public final static Property Pic = new Property(4, String.class, "Pic", false, "PIC");
    }


    public ArtistDao(DaoConfig config) {
        super(config);
    }
    
    public ArtistDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Id
                "\"USER_ID\" INTEGER," + // 1: UserId
                "\"ARTIST_ID\" INTEGER," + // 2: ArtistId
                "\"NAME\" TEXT," + // 3: Name
                "\"PIC\" TEXT);"); // 4: Pic
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Artist entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(2, UserId);
        }
 
        Long ArtistId = entity.getArtistId();
        if (ArtistId != null) {
            stmt.bindLong(3, ArtistId);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(4, Name);
        }
 
        String Pic = entity.getPic();
        if (Pic != null) {
            stmt.bindString(5, Pic);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Artist entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(2, UserId);
        }
 
        Long ArtistId = entity.getArtistId();
        if (ArtistId != null) {
            stmt.bindLong(3, ArtistId);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(4, Name);
        }
 
        String Pic = entity.getPic();
        if (Pic != null) {
            stmt.bindString(5, Pic);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Artist readEntity(Cursor cursor, int offset) {
        Artist entity = new Artist( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // UserId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // ArtistId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // Pic
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Artist entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setArtistId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPic(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Artist entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Artist entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Artist entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
