package com.jqwong.music.repository.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jqwong.music.repository.entity.HotSearch;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOT_SEARCH".
*/
public class HotSearchDao extends AbstractDao<HotSearch, Long> {

    public static final String TABLENAME = "HOT_SEARCH";

    /**
     * Properties of entity HotSearch.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property Key = new Property(1, String.class, "Key", false, "KEY");
        public final static Property Date = new Property(2, String.class, "Date", false, "DATE");
    }


    public HotSearchDao(DaoConfig config) {
        super(config);
    }
    
    public HotSearchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOT_SEARCH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Id
                "\"KEY\" TEXT," + // 1: Key
                "\"DATE\" TEXT);"); // 2: Date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOT_SEARCH\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HotSearch entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String Key = entity.getKey();
        if (Key != null) {
            stmt.bindString(2, Key);
        }
 
        String Date = entity.getDate();
        if (Date != null) {
            stmt.bindString(3, Date);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HotSearch entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String Key = entity.getKey();
        if (Key != null) {
            stmt.bindString(2, Key);
        }
 
        String Date = entity.getDate();
        if (Date != null) {
            stmt.bindString(3, Date);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HotSearch readEntity(Cursor cursor, int offset) {
        HotSearch entity = new HotSearch( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Key
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // Date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HotSearch entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HotSearch entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HotSearch entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HotSearch entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
