package com.jqwong.music.dal.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jqwong.music.entity.FavoriteMedia;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAVORITE_MEDIA".
*/
public class FavoriteMediaDao extends AbstractDao<FavoriteMedia, Long> {

    public static final String TABLENAME = "FAVORITE_MEDIA";

    /**
     * Properties of entity FavoriteMedia.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property Rid = new Property(1, Integer.class, "Rid", false, "RID");
        public final static Property UserUUID = new Property(2, String.class, "UserUUID", false, "USER_UUID");
    }


    public FavoriteMediaDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteMediaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAVORITE_MEDIA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"RID\" INTEGER," + // 1: Rid
                "\"USER_UUID\" TEXT);"); // 2: UserUUID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAVORITE_MEDIA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FavoriteMedia entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Integer Rid = entity.getRid();
        if (Rid != null) {
            stmt.bindLong(2, Rid);
        }
 
        String UserUUID = entity.getUserUUID();
        if (UserUUID != null) {
            stmt.bindString(3, UserUUID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FavoriteMedia entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        Integer Rid = entity.getRid();
        if (Rid != null) {
            stmt.bindLong(2, Rid);
        }
 
        String UserUUID = entity.getUserUUID();
        if (UserUUID != null) {
            stmt.bindString(3, UserUUID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FavoriteMedia readEntity(Cursor cursor, int offset) {
        FavoriteMedia entity = new FavoriteMedia( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // Rid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // UserUUID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FavoriteMedia entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRid(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setUserUUID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FavoriteMedia entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FavoriteMedia entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FavoriteMedia entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
