package com.jqwong.music.dal.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jqwong.music.entity.Media;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDIA".
*/
public class MediaDao extends AbstractDao<Media, Long> {

    public static final String TABLENAME = "MEDIA";

    /**
     * Properties of entity Media.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property MusicRid = new Property(1, String.class, "MusicRid", false, "MUSIC_RID");
        public final static Property Rid = new Property(2, Integer.class, "Rid", false, "RID");
        public final static Property Artist = new Property(3, String.class, "Artist", false, "ARTIST");
        public final static Property Pic = new Property(4, String.class, "Pic", false, "PIC");
        public final static Property Album = new Property(5, String.class, "Album", false, "ALBUM");
        public final static Property AlbumId = new Property(6, Integer.class, "AlbumId", false, "ALBUM_ID");
        public final static Property Name = new Property(7, String.class, "Name", false, "NAME");
        public final static Property Pic120 = new Property(8, String.class, "Pic120", false, "PIC120");
        public final static Property SongTimeMinutes = new Property(9, String.class, "SongTimeMinutes", false, "SONG_TIME_MINUTES");
        public final static Property Time = new Property(10, Long.class, "Time", false, "TIME");
        public final static Property Url = new Property(11, String.class, "Url", false, "URL");
        public final static Property ArtistId = new Property(12, Long.class, "ArtistId", false, "ARTIST_ID");
    }


    public MediaDao(DaoConfig config) {
        super(config);
    }
    
    public MediaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDIA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"MUSIC_RID\" TEXT," + // 1: MusicRid
                "\"RID\" INTEGER," + // 2: Rid
                "\"ARTIST\" TEXT," + // 3: Artist
                "\"PIC\" TEXT," + // 4: Pic
                "\"ALBUM\" TEXT," + // 5: Album
                "\"ALBUM_ID\" INTEGER," + // 6: AlbumId
                "\"NAME\" TEXT," + // 7: Name
                "\"PIC120\" TEXT," + // 8: Pic120
                "\"SONG_TIME_MINUTES\" TEXT," + // 9: SongTimeMinutes
                "\"TIME\" INTEGER," + // 10: Time
                "\"URL\" TEXT," + // 11: Url
                "\"ARTIST_ID\" INTEGER);"); // 12: ArtistId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDIA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Media entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String MusicRid = entity.getMusicRid();
        if (MusicRid != null) {
            stmt.bindString(2, MusicRid);
        }
 
        Integer Rid = entity.getRid();
        if (Rid != null) {
            stmt.bindLong(3, Rid);
        }
 
        String Artist = entity.getArtist();
        if (Artist != null) {
            stmt.bindString(4, Artist);
        }
 
        String Pic = entity.getPic();
        if (Pic != null) {
            stmt.bindString(5, Pic);
        }
 
        String Album = entity.getAlbum();
        if (Album != null) {
            stmt.bindString(6, Album);
        }
 
        Integer AlbumId = entity.getAlbumId();
        if (AlbumId != null) {
            stmt.bindLong(7, AlbumId);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(8, Name);
        }
 
        String Pic120 = entity.getPic120();
        if (Pic120 != null) {
            stmt.bindString(9, Pic120);
        }
 
        String SongTimeMinutes = entity.getSongTimeMinutes();
        if (SongTimeMinutes != null) {
            stmt.bindString(10, SongTimeMinutes);
        }
 
        Long Time = entity.getTime();
        if (Time != null) {
            stmt.bindLong(11, Time);
        }
 
        String Url = entity.getUrl();
        if (Url != null) {
            stmt.bindString(12, Url);
        }
 
        Long ArtistId = entity.getArtistId();
        if (ArtistId != null) {
            stmt.bindLong(13, ArtistId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Media entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String MusicRid = entity.getMusicRid();
        if (MusicRid != null) {
            stmt.bindString(2, MusicRid);
        }
 
        Integer Rid = entity.getRid();
        if (Rid != null) {
            stmt.bindLong(3, Rid);
        }
 
        String Artist = entity.getArtist();
        if (Artist != null) {
            stmt.bindString(4, Artist);
        }
 
        String Pic = entity.getPic();
        if (Pic != null) {
            stmt.bindString(5, Pic);
        }
 
        String Album = entity.getAlbum();
        if (Album != null) {
            stmt.bindString(6, Album);
        }
 
        Integer AlbumId = entity.getAlbumId();
        if (AlbumId != null) {
            stmt.bindLong(7, AlbumId);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(8, Name);
        }
 
        String Pic120 = entity.getPic120();
        if (Pic120 != null) {
            stmt.bindString(9, Pic120);
        }
 
        String SongTimeMinutes = entity.getSongTimeMinutes();
        if (SongTimeMinutes != null) {
            stmt.bindString(10, SongTimeMinutes);
        }
 
        Long Time = entity.getTime();
        if (Time != null) {
            stmt.bindLong(11, Time);
        }
 
        String Url = entity.getUrl();
        if (Url != null) {
            stmt.bindString(12, Url);
        }
 
        Long ArtistId = entity.getArtistId();
        if (ArtistId != null) {
            stmt.bindLong(13, ArtistId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Media readEntity(Cursor cursor, int offset) {
        Media entity = new Media( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // MusicRid
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // Rid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Artist
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Pic
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Album
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // AlbumId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Name
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // Pic120
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // SongTimeMinutes
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // Time
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // Url
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12) // ArtistId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Media entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMusicRid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRid(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setArtist(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPic(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAlbum(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAlbumId(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPic120(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSongTimeMinutes(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTime(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setUrl(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setArtistId(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Media entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Media entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Media entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
