package com.jqwong.music.dal.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jqwong.music.entity.SheetInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHEET_INFO".
*/
public class SheetInfoDao extends AbstractDao<SheetInfo, Long> {

    public static final String TABLENAME = "SHEET_INFO";

    /**
     * Properties of entity SheetInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property UserUUID = new Property(1, String.class, "UserUUID", false, "USER_UUID");
        public final static Property SheetToken = new Property(2, String.class, "SheetToken", false, "SHEET_TOKEN");
        public final static Property Rid = new Property(3, String.class, "Rid", false, "RID");
    }


    public SheetInfoDao(DaoConfig config) {
        super(config);
    }
    
    public SheetInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHEET_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"USER_UUID\" TEXT," + // 1: UserUUID
                "\"SHEET_TOKEN\" TEXT," + // 2: SheetToken
                "\"RID\" TEXT);"); // 3: Rid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHEET_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SheetInfo entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String UserUUID = entity.getUserUUID();
        if (UserUUID != null) {
            stmt.bindString(2, UserUUID);
        }
 
        String SheetToken = entity.getSheetToken();
        if (SheetToken != null) {
            stmt.bindString(3, SheetToken);
        }
 
        String Rid = entity.getRid();
        if (Rid != null) {
            stmt.bindString(4, Rid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SheetInfo entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String UserUUID = entity.getUserUUID();
        if (UserUUID != null) {
            stmt.bindString(2, UserUUID);
        }
 
        String SheetToken = entity.getSheetToken();
        if (SheetToken != null) {
            stmt.bindString(3, SheetToken);
        }
 
        String Rid = entity.getRid();
        if (Rid != null) {
            stmt.bindString(4, Rid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SheetInfo readEntity(Cursor cursor, int offset) {
        SheetInfo entity = new SheetInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UserUUID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // SheetToken
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // Rid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SheetInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserUUID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSheetToken(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SheetInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SheetInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SheetInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
